### ISSUE TITLE
"Missing token" Error on several default keyboard layouts. 

### ISSUE THREAD

**Issue by wdpk** [Ciantic/qmkmapper#5]
For several keyboards, the default layout in the keymap.c attempts to follow the physical pattern of the keys. They include backslashes at the end of the line. The final one between the last key and the closing of the layer parenthesis causes a "missing token" error. Deleting this final backslash seems to resolve the issue. 
This happens with;
IDOBO - my keyboard;
these I just selected from the dropdown until there was an error;
Hadron
Frosty Flake
Espectro

The keymap.c compiles and works fine with the backslash.

**Comment by Ciantic** [comment]
Yes. Currently this is by design. I don't intend to parse C. My parser is very naive. You can just remove the backslash from the end of the line if you wish, it's useless anyway.
