### ISSUE TITLE
Doesn't work with Let's Split

### ISSUE THREAD

**Issue by LazaroFilm** [Ciantic/qmkmapper#7]
I tried to load the Let's Split layout and I get an error both on VS Code and the Browser version. 
`This keymap.c has different amount of keys than in a chosen keyboard`
`Missing token at: 2032`

**Comment by Ciantic** [comment]
Do you use \ at the end of code line? Sometimes the layout you give is not parseable because my parser is not C compliant, one of things is escaping. It can't handle new line escaping.

**Comment by Ciantic** [comment]
Remove these:

![image](https://user-images.githubusercontent.com/64731/101105919-77423300-35d7-11eb-92b7-1ffa557a1729.png)


Ant it will work, you can try it here: http://ciantic.github.io/keymapceditor/#lets_split||https%3A%2F%2Fraw.githubusercontent.com%2Fqmk%2Fqmk_firmware%2F91e8e8d916eca4fb9db69876d91d7987946cf540%2Fkeyboards%2Flets_split%2Fkeymaps%2Fdefault%2Fkeymap.c

The example file has same problem. Useless \ chars.
